### ISSUE TITLE
DataFrame Tracer

### ISSUE THREAD

**Issue by iblislin** [JuliaML/LearningStrategies.jl#16]
It will be good if the underlying of Tracer is a DataFrame.
User can `push!` several values into that Tracer in a single function call.

**Comment by joshday** [comment]
I don't think I completely follow you, but picking up a DataFrames dependency is too much.  Can you explain what you mean?

**Comment by iblislin** [comment]
I tried this:
```julia
struct DFTracer <: LearningStrategy
  f
  b::Int
  df::DataFrame

  DFTracer(T::Vector{<:Type}, names::Vector{Symbol}, f, b = 1) =
    new(f, b, DataFrame(T, names, 0))
end

function hook(t::DFTracer, m, i)
  (mod1(i, t.b) == t.b) && push!(t.df, t.f(m, i))
  nothing
end
```

and I use it like this
```julia
dftracer = DFTracer([Float64, Symbol], [:reward, :action], (x, i) -> begin
      ...
    end,
20)
```

> but picking up a DataFrames dependency is too much

yeah, maybe we can make DataFrames as optional dependency via Require.jl?

**Comment by joshday** [comment]
If you use a `Tracer` `t` with a function that returns a tuple `(reward, action)`, this just saves a single line of code, right?  

```julia
DataFrame(reward = first.(collect(t)), action = last.(collect(t))]
```

I think pushing to a tabular data structure is probably "too specific" a feature, considering we already have `Tracer` that gives you the data as a vector that you can then convert to whatever structure you want.

The great part about LearningStrategies is that making a new strategy is easy, so if you want to specifically push to a DataFrame, you just got that with a few lines of code.  Since LearningStrategies is so easy to extend, I'd rather show people how to make their own strategies vs. offer every possible strategy one would want.

**Comment by iblislin** [comment]
> If you use a Tracer t with a function that returns a tuple (reward, action), this just saves a single line of code, right?

In my personal usage, I need to return a quite large tuple which has more than 4 element.
That's why I decide to use DataFrame.

> I think pushing to a tabular data structure is probably "too specific" a feature, considering we already have Tracer that gives you the data as a vector that you can then convert to whatever structure you want.
> 
> The great part about LearningStrategies is that making a new strategy is easy, so if you want to specifically push to a DataFrame, you just got that with a few lines of code. Since LearningStrategies is so easy to extend, I'd rather show people how to make their own strategies vs. offer every possible strategy one would want.

Now, I'm using my `DFTracer` happily. I'm also willing to contribute it. Where is the best place to put these code?

**Comment by joshday** [comment]
> Now, I'm using my DFTracer happily. I'm also willing to contribute it. Where is the best place to put these code?

Okay cool.  How about in a an examples directory?

**Comment by joshday** [comment]
Or even the README.  At some point I should hook up documenter and then it can go in the docs.
